# Generated by Django 3.0.5 on 2020-04-05 15:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todolists', '0002_auto_20200401_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todolist',
            name='details',
            field=models.TextField(default='hello'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todolist',
            name='remind_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todolist',
            name='item',
            field=models.CharField(max_length=100),
        ),
    ]
